version: '3'

services:

  grocy:
    image: linuxserver/grocy
    restart: always
    volumes:
      - grocy-data:/config
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      GROCY_CULTURE: de
    logging:
      options:
        max-size: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.grocy-web.loadbalancer.server.url=http://grocy:80"
      # HTTP
      - "traefik.http.routers.grocy-web.rule=Host(`${DOMAINS_GROCY}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_GROCY}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.grocy-web.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.grocy-secured.rule=Host(`${DOMAINS_GROCY}.${DOMAINS_BASE}`) || Host(`www.${DOMAINS_GROCY}.${DOMAINS_BASE}`)"
      - "traefik.http.routers.grocy-secured.entrypoints=web-secured"
      - "traefik.http.routers.grocy-secured.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Sonstige
      - homepage.name=Grocy
      - homepage.href=https://${DOMAINS_GROCY}.${DOMAINS_BASE}
      - homepage.description=Lebensmittelverwaltung

networks:
  web:
    external: true

volumes:
  grocy-data: