version: "3"

services:

  resolve-db:
    image: postgres:16-alpine
    restart: always
    networks:
      - web
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 20m
    secrets:
      - resolve-db_username
      - resolve-db_password
    environment:
      POSTGRES_DB: resolve-db
      POSTGRES_USER_FILE: /run/secrets/resolve-db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/resolve-db_password
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.tcp.services.resolve-db.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.resolve-db.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.resolve-db.rule=HostSNI(`${DOMAINS_RESOLVEDB}.${DOMAINS_BASE}`)"
      - "traefik.tcp.routers.resolve-db.entrypoints=pgsql"
      - "traefik.tcp.routers.resolve-db.service=resolve-db"
      # - "traefik.tcp.routers.resolve-db.tls.certresolver=tlschallenge"
      # Homepage
      - homepage.group=Server-Management
      - homepage.name=Resolve DB
      - homepage.description=Datenbank f√ºr DaVinci Resolve
      - homepage.icon=si-postgresql

secrets:
  resolve-db_username:
    file: ../secrets/resolve-db_username
  resolve-db_password:
    file: ../secrets/resolve-db_password

volumes:
  db:

networks:
  web:
    external: true